setwd("~/GitHub/PFA/Data-visualization")
library(bmp)
pic <- read.bmp(f = '1pixel.bmp')
pic <- read.bmp("3x1-horizontal.bmp")
pic <- read.bmp("1x3-vertical.bmp")
pic <- read.bmp("3x3-pixels.bmp")
pic <- read.bmp("bits.bmp")
print(pic[,,])
write.csv(pic, file = "bits.csv")
